SKILLS_DB = [
    "python",
    "java",
    "c++",
    "javascript",
    "typescript",
    "react",
    "angular",
    "vue",
    "nodejs",
    "express",
    "mongodb",
    "mysql",
    "postgresql",
    "sql",
    "html",
    "css",
    "git",
    "github",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "machine learning",
    "deep learning",
    "data science",
    "flask",
    "django",
    "streamlit",
    "pandas",
    "numpy",
    "tensorflow",
    "pytorch"
]